{
 "title": "RedSea 300 G2+",
 "description": "Apex System for Red Sea 300 G2+",
 "time": { "from": "2025-12-04T15:05:14.658Z", "to": "2025-12-11T15:05:14.658Z" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alk",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Alkx4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Alk Stat\")"
    }
   ]
  },
  {
   "title": "Alkalinity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dKH" } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Alkx4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Alkalinity\")"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Tmp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Temperature\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Tmp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Temperature\")"
    }
   ]
  },
  {
   "title": "Calc",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Cax4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Calc Stat\")"
    }
   ]
  },
  {
   "title": "Calcium",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Cax4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Calcium\")"
    }
   ]
  },
  {
   "title": "Current pH",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"pH\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"pH\")"
    }
   ]
  },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"pH\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Tank pH\")"
    }
   ]
  },
  {
   "title": "Mag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Mgx4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Mag\")"
    }
   ]
  },
  {
   "title": "Magnesium ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"Mgx4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Magnesium\")"
    }
   ]
  },
  {
   "title": "Current ORP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"ORP\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"ORP\")"
    }
   ]
  },
  {
   "title": "ORP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"apex_datalog\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apex_probes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\") \n  |> filter(fn: (r) => r[\"probe_id\"] == \"ORP\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"ORP\")"
    }
   ]
  }
 ]
}